# Don't add a newline at the end
add_newline = false

[character]
success_symbol = "[ğ›Œ](bold green)"
error_symbol = ""

[status]
disabled = false
style = "bold red"
symbol = "ğ›Œ"
format = "[$symbol\\($status\\)]($style)"
